spring:
  application:
    name: find_demo
  mvc:
    view:
      prefix: /
      suffix: .html
  http:
    encoding:
      force: true
  datasource:
    #    数据源配置
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://47.100.37.7:5432/postgres?characterEncoding=utf-8\
    username: postgres
    password: zhang002508
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 60000
      validation-query: "select 1"
      validation-query-timeout: 600000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      filters: stat
      stat-view-servlet:
        login-username: admin
        login-password: zhang002508
        enabled: true # 开启之后才能使用控制台


server:
  port: 5757
  servlet:
    context-path: /
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 154.8.194.71:22122

mybatis-plus:
#  type-aliases-package: com.find.pojo
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto
  type-handlers-package: com.find.TypeHandler
#  mapper-locations: com/find/mapper/*.xml
#  mapper-locations: com.find.mapper.*.xml
# mybatis中的日志默认在debug级别开启，因此要设置日志级别
logging:
  level:
    web: info
    com:
      find:
        mapper: info